version: "3.8"
services:
 
  postgres_db:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD : postgres
      POSTGRES_USER : postgres
      PSTGRES_DB : postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes: 
      - pgdata:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer:4.7
    ports:
      - 8080:8080
    depends_on:
      postgres_db:
        condition: service_healthy

  node_app:
    container_name: node_pg
    build: .
    ports:
      - "3000:3000"
    environment:
      - PG_DB=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=postgres_db
      - PORT=3000
    depends_on:
        postgres_db:
          condition: service_healthy
    restart: always

      
volumes:
  pgdata:
    driver: local